version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER={your_username}
      - POSTGRES_PASSWORD={your_password}
      - POSTGRES_DB={your-pg-database}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - {create_your_network}
    restart: unless-stopped

  backend:
    build: ./AnthraServer
    image: anthra-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - anthra-network
    restart: unless-stopped

  frontend:
    build: ./AnthraClient
    image: anthra-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - anthra-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - anthra-network
    restart: unless-stopped
    profiles:
      - production  

volumes:
  db_data:

networks:
  anthra-network:
