version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=anthra_user
      - POSTGRES_PASSWORD=jelkokelkojelkomerlin
      - POSTGRES_DB=anthra
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./AnthraServer
    image: anthra-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "443:443" # Expose HTTPS port
    volumes:
      - ./AnthraServer/certificate.pem:/certificate.pem
      - ./AnthraServer/private.key:/private.key
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./AnthraClient
    image: anthra-frontend
    ports:
      - "80:80" # Expose HTTP port for the frontend
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
